// Auto-generated web assets
#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

const char INDEX_HTML[] = 
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "    <title>ESP32 WiFi Sniffer</title>\n"
    "    <link rel=\"stylesheet\" href=\"style.css\">\n"
    "</head>\n"
    "<body>\n"
    "    <div class=\"container\">\n"
    "        <header>\n"
    "            <h1>🔍 ESP32 WiFi Sniffer</h1>\n"
    "            <div class=\"status-bar\">\n"
    "                <span id=\"connection-status\" class=\"status disconnected\">Disconnected</span>\n"
    "                <span id=\"mode-badge\" class=\"badge\">IDLE</span>\n"
    "                <button id=\"lang-toggle\" class=\"lang-btn\" onclick=\"toggleLanguage()\">EN | 中文</button>\n"
    "            </div>\n"
    "        </header>\n"
    "\n"
    "        <nav class=\"tabs\">\n"
    "            <button class=\"tab-btn active\" data-tab=\"dashboard\">Statistics</button>\n"
    "            <button class=\"tab-btn\" data-tab=\"networks\">Networks</button>\n"
    "            <button class=\"tab-btn\" data-tab=\"capture\">Capture</button>\n"
    "            <button class=\"tab-btn\" data-tab=\"attack\">Attack</button>\n"
    "            <button class=\"tab-btn\" data-tab=\"logs\">Logs</button>\n"
    "        </nav>\n"
    "\n"
    "        <main>\n"
    "            <!-- Dashboard Tab -->\n"
    "            <section id=\"dashboard\" class=\"tab-content active\">\n"
    "                <div class=\"card-grid\">\n"
    "                    <div class=\"card\">\n"
    "                        <h3>📊 Statistics</h3>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">Total Packets:</span>\n"
    "                            <span id=\"stat-packets\" class=\"stat-value\">0</span>\n"
    "                        </div>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">Networks Found:</span>\n"
    "                            <span id=\"stat-networks\" class=\"stat-value\">0</span>\n"
    "                        </div>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">Current Channel:</span>\n"
    "                            <span id=\"stat-channel\" class=\"stat-value\">1</span>\n"
    "                        </div>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">RSSI:</span>\n"
    "                            <span id=\"stat-rssi\" class=\"stat-value\">-</span>\n"
    "                        </div>\n"
    "                    </div>\n"
    "\n"
    "                    <div class=\"card\">\n"
    "                        <h3>📡 WiFi Info</h3>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">AP IP:</span>\n"
    "                            <span id=\"wifi-ip\" class=\"stat-value\">192.168.4.1</span>\n"
    "                        </div>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">Connected Clients:</span>\n"
    "                            <span id=\"wifi-clients\" class=\"stat-value\">0</span>\n"
    "                        </div>\n"
    "                        <div class=\"stat-row\">\n"
    "                            <span class=\"stat-label\">Uptime:</span>\n"
    "                            <span id=\"stat-uptime\" class=\"stat-value\">00:00:00</span>\n"
    "                        </div>\n"
    "                    </div>\n"
    "\n"
    "                    <div class=\"card\">\n"
    "                        <h3>🎯 Quick Actions</h3>\n"
    "                        <div class=\"button-group\">\n"
    "                            <button id=\"btn-scan\" class=\"btn btn-primary\">Start Scan</button>\n"
    "                            <button id=\"btn-sniff\" class=\"btn btn-secondary\">Start Sniff</button>\n"
    "                            <button id=\"btn-reset\" class=\"btn btn-danger\">Reset</button>\n"
    "                        </div>\n"
    "                    </div>\n"
    "                </div>\n"
    "\n"
    "                <div class=\"card\">\n"
    "                    <h3>📈 Packet Rate</h3>\n"
    "                    <canvas id=\"packet-chart\" width=\"800\" height=\"200\"></canvas>\n"
    "                </div>\n"
    "            </section>\n"
    "\n"
    "            <!-- Networks Tab -->\n"
    "            <section id=\"networks\" class=\"tab-content\">\n"
    "                <div class=\"toolbar\">\n"
    "                    <button id=\"btn-refresh-networks\" class=\"btn btn-primary\">🔄 Refresh</button>\n"
    "                    <input type=\"text\" id=\"network-filter\" placeholder=\"Filter networks...\">\n"
    "                </div>\n"
    "                <div class=\"table-container\">\n"
    "                    <table id=\"networks-table\">\n"
    "                        <thead>\n"
    "                            <tr>\n"
    "                                <th>SSID</th>\n"
    "                                <th>BSSID</th>\n"
    "                                <th>Channel</th>\n"
    "                                <th>RSSI</th>\n"
    "                                <th>Security</th>\n"
    "                                <th>Packets</th>\n"
    "                                <th>Actions</th>\n"
    "                            </tr>\n"
    "                        </thead>\n"
    "                        <tbody id=\"networks-tbody\">\n"
    "                            <!-- Dynamic content -->\n"
    "                        </tbody>\n"
    "                    </table>\n"
    "                </div>\n"
    "            </section>\n"
    "\n"
    "            <!-- Capture Tab -->\n"
    "            <section id=\"capture\" class=\"tab-content\">\n"
    "                <div class=\"card-grid\">\n"
    "                    <div class=\"card\">\n"
    "                        <h3>📦 Capture Control</h3>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Channel:</label>\n"
    "                            <select id=\"capture-channel\">\n"
    "                                <option value=\"0\">All (Hop)</option>\n"
    "                                ${Array.from({length: 14}, (_, i) => `<option value=\"${i+1}\">${i+1}</option>`).join('')}\n"
    "                            </select>\n"
    "                        </div>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Target BSSID:</label>\n"
    "                            <input type=\"text\" id=\"capture-bssid\" placeholder=\"AA:BB:CC:DD:EE:FF\">\n"
    "                        </div>\n"
    "                        <div class=\"button-group\">\n"
    "                            <button id=\"btn-capture-start\" class=\"btn btn-success\">▶️ Start</button>\n"
    "                            <button id=\"btn-capture-stop\" class=\"btn btn-danger\">⏹️ Stop</button>\n"
    "                        </div>\n"
    "                    </div>\n"
    "\n"
    "                    <div class=\"card\">\n"
    "                        <h3>🤝 Handshake Capture</h3>\n"
    "                        <div id=\"handshake-status\" class=\"handshake-indicator\">\n"
    "                            <div class=\"msg-indicator\" id=\"msg1\">M1</div>\n"
    "                            <div class=\"msg-indicator\" id=\"msg2\">M2</div>\n"
    "                            <div class=\"msg-indicator\" id=\"msg3\">M3</div>\n"
    "                            <div class=\"msg-indicator\" id=\"msg4\">M4</div>\n"
    "                        </div>\n"
    "                        <div class=\"progress-bar\">\n"
    "                            <div id=\"handshake-progress\" class=\"progress-fill\" style=\"width: 0%\"></div>\n"
    "                        </div>\n"
    "                        <p id=\"handshake-text\">No handshake captured</p>\n"
    "                        <button id=\"btn-download-handshake\" class=\"btn btn-primary\" disabled>⬇️ Download</button>\n"
    "                    </div>\n"
    "                </div>\n"
    "\n"
    "                <div class=\"card\">\n"
    "                    <h3>💾 Files</h3>\n"
    "                    <div id=\"file-list\" class=\"file-list\">\n"
    "                        <!-- Dynamic content -->\n"
    "                    </div>\n"
    "                </div>\n"
    "            </section>\n"
    "\n"
    "            <!-- Attack Tab -->\n"
    "            <section id=\"attack\" class=\"tab-content\">\n"
    "                <div class=\"warning-box\">\n"
    "                    ⚠️ <strong>Warning:</strong> These features are for authorized security testing only!\n"
    "                </div>\n"
    "\n"
    "                <div class=\"card-grid\">\n"
    "                    <div class=\"card\">\n"
    "                        <h3>💥 Deauth Attack</h3>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Target BSSID:</label>\n"
    "                            <input type=\"text\" id=\"deauth-bssid\" placeholder=\"AA:BB:CC:DD:EE:FF\">\n"
    "                        </div>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Target Station (optional):</label>\n"
    "                            <input type=\"text\" id=\"deauth-station\" placeholder=\"AA:BB:CC:DD:EE:FF\">\n"
    "                        </div>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Reason Code:</label>\n"
    "                            <select id=\"deauth-reason\">\n"
    "                                <option value=\"7\">Class 3 frame from nonassociated STA (7)</option>\n"
    "                                <option value=\"6\">Class 2 frame from nonauthenticated STA (6)</option>\n"
    "                                <option value=\"1\">Unspecified (1)</option>\n"
    "                                <option value=\"2\">Previous auth no longer valid (2)</option>\n"
    "                                <option value=\"3\">Deauth leaving (3)</option>\n"
    "                                <option value=\"4\">Disassoc due to inactivity (4)</option>\n"
    "                                <option value=\"5\">Disassoc AP busy (5)</option>\n"
    "                            </select>\n"
    "                        </div>\n"
    "                        <div class=\"button-group\">\n"
    "                            <button id=\"btn-deauth-start\" class=\"btn btn-danger\">⚠️ Start Deauth</button>\n"
    "                            <button id=\"btn-deauth-stop\" class=\"btn btn-secondary\">Stop</button>\n"
    "                        </div>\n"
    "                        <div id=\"deauth-stats\" class=\"stats-text\"></div>\n"
    "                    </div>\n"
    "\n"
    "                    <div class=\"card\">\n"
    "                        <h3>🔓 Dictionary Attack</h3>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Handshake File:</label>\n"
    "                            <select id=\"dict-handshake\">\n"
    "                                <option value=\"\">Select handshake...</option>\n"
    "                            </select>\n"
    "                        </div>\n"
    "                        <div class=\"form-group\">\n"
    "                            <label>Dictionary:</label>\n"
    "                            <select id=\"dict-file\">\n"
    "                                <option value=\"\">Select dictionary...</option>\n"
    "                                <option value=\"/sdcard/wordlist.txt\">wordlist.txt</option>\n"
    "                            </select>\n"
    "                        </div>\n"
    "                        <div class=\"button-group\">\n"
    "                            <button id=\"btn-dict-start\" class=\"btn btn-primary\">▶️ Start Attack</button>\n"
    "                            <button id=\"btn-dict-stop\" class=\"btn btn-secondary\">Stop</button>\n"
    "                        </div>\n"
    "                        <div id=\"dict-progress\" class=\"progress-bar\">\n"
    "                            <div class=\"progress-fill\" style=\"width: 0%\"></div>\n"
    "                        </div>\n"
    "                        <div id=\"dict-stats\" class=\"stats-text\"></div>\n"
    "                    </div>\n"
    "                </div>\n"
    "            </section>\n"
    "\n"
    "            <!-- Logs Tab -->\n"
    "            <section id=\"logs\" class=\"tab-content\">\n"
    "                <div class=\"toolbar\">\n"
    "                    <button id=\"btn-clear-logs\" class=\"btn btn-secondary\">Clear</button>\n"
    "                    <button id=\"btn-export-logs\" class=\"btn btn-primary\">Export</button>\n"
    "                    <select id=\"log-level\">\n"
    "                        <option value=\"all\">All Levels</option>\n"
    "                        <option value=\"error\">Error</option>\n"
    "                        <option value=\"warn\">Warning</option>\n"
    "                        <option value=\"info\">Info</option>\n"
    "                        <option value=\"debug\">Debug</option>\n"
    "                    </select>\n"
    "                </div>\n"
    "                <div id=\"log-container\" class=\"log-container\">\n"
    "                    <!-- Dynamic content -->\n"
    "                </div>\n"
    "            </section>\n"
    "        </main>\n"
    "\n"
    "        <footer>\n"
    "            <p>ESP32 WiFi Sniffer v1.0.0 | For security research only</p>\n"
    "        </footer>\n"
    "    </div>\n"
    "\n"
    "    <script src=\"app.js\"></script>\n"
    "</body>\n"
    "</html>\n"
    "\n";

const char STYLE_CSS[] = 
    "/**\n"
    " * ESP32 WiFi Sniffer - Styles\n"
    " */\n"
    "\n"
    ":root {\n"
    "    --bg-primary: #1a1a2e;\n"
    "    --bg-secondary: #16213e;\n"
    "    --bg-card: #0f3460;\n"
    "    --text-primary: #eaeaea;\n"
    "    --text-secondary: #a0a0a0;\n"
    "    --accent-primary: #e94560;\n"
    "    --accent-success: #4CAF50;\n"
    "    --accent-warning: #FFC107;\n"
    "    --accent-danger: #f44336;\n"
    "    --accent-info: #2196F3;\n"
    "    --border-radius: 8px;\n"
    "    --transition: all 0.3s ease;\n"
    "}\n"
    "\n"
    "* {\n"
    "    margin: 0;\n"
    "    padding: 0;\n"
    "    box-sizing: border-box;\n"
    "}\n"
    "\n"
    "body {\n"
    "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
    "    background: var(--bg-primary);\n"
    "    color: var(--text-primary);\n"
    "    min-height: 100vh;\n"
    "    line-height: 1.6;\n"
    "}\n"
    "\n"
    ".container {\n"
    "    max-width: 1200px;\n"
    "    margin: 0 auto;\n"
    "    padding: 20px;\n"
    "}\n"
    "\n"
    "/* Header */\n"
    "header {\n"
    "    text-align: center;\n"
    "    padding: 20px 0;\n"
    "    border-bottom: 2px solid var(--bg-card);\n"
    "    margin-bottom: 20px;\n"
    "}\n"
    "\n"
    "header h1 {\n"
    "    font-size: 2rem;\n"
    "    margin-bottom: 10px;\n"
    "    background: linear-gradient(45deg, var(--accent-primary), var(--accent-info));\n"
    "    -webkit-background-clip: text;\n"
    "    -webkit-text-fill-color: transparent;\n"
    "    background-clip: text;\n"
    "}\n"
    "\n"
    ".status-bar {\n"
    "    display: flex;\n"
    "    justify-content: center;\n"
    "    gap: 15px;\n"
    "    align-items: center;\n"
    "}\n"
    "\n"
    ".lang-btn {\n"
    "    padding: 5px 14px;\n"
    "    border-radius: 6px;\n"
    "    border: 1px solid rgba(255,255,255,0.35);\n"
    "    background: rgba(255,255,255,0.12);\n"
    "    color: #e0e0e0;\n"
    "    font-size: 0.78rem;\n"
    "    cursor: pointer;\n"
    "    transition: all 0.2s;\n"
    "    letter-spacing: 0.5px;\n"
    "    font-weight: 500;\n"
    "}\n"
    ".lang-btn:hover {\n"
    "    background: rgba(255,255,255,0.25);\n"
    "    color: #fff;\n"
    "    border-color: rgba(255,255,255,0.6);\n"
    "}\n"
    "\n"
    ".status {\n"
    "    padding: 5px 15px;\n"
    "    border-radius: 20px;\n"
    "    font-size: 0.85rem;\n"
    "    font-weight: bold;\n"
    "}\n"
    "\n"
    ".status.connected {\n"
    "    background: var(--accent-success);\n"
    "    color: #000;\n"
    "}\n"
    "\n"
    ".status.disconnected {\n"
    "    background: var(--accent-danger);\n"
    "    color: #fff;\n"
    "}\n"
    "\n"
    ".badge {\n"
    "    background: var(--bg-card);\n"
    "    padding: 5px 15px;\n"
    "    border-radius: 20px;\n"
    "    font-size: 0.85rem;\n"
    "    font-weight: bold;\n"
    "    color: var(--accent-info);\n"
    "}\n"
    "\n"
    "/* Tabs */\n"
    ".tabs {\n"
    "    display: flex;\n"
    "    gap: 5px;\n"
    "    margin-bottom: 20px;\n"
    "    background: var(--bg-secondary);\n"
    "    padding: 5px;\n"
    "    border-radius: var(--border-radius);\n"
    "    overflow-x: auto;\n"
    "}\n"
    "\n"
    ".tab-btn {\n"
    "    flex: 1;\n"
    "    padding: 12px 20px;\n"
    "    background: transparent;\n"
    "    border: none;\n"
    "    color: var(--text-secondary);\n"
    "    cursor: pointer;\n"
    "    border-radius: var(--border-radius);\n"
    "    transition: var(--transition);\n"
    "    font-size: 0.9rem;\n"
    "    white-space: nowrap;\n"
    "    min-width: 100px;\n"
    "}\n"
    "\n"
    ".tab-btn:hover {\n"
    "    background: rgba(255, 255, 255, 0.1);\n"
    "    color: var(--text-primary);\n"
    "}\n"
    "\n"
    ".tab-btn.active {\n"
    "    background: var(--accent-primary);\n"
    "    color: #fff;\n"
    "}\n"
    "\n"
    "/* Tab Content */\n"
    ".tab-content {\n"
    "    display: none;\n"
    "    animation: fadeIn 0.3s ease;\n"
    "}\n"
    "\n"
    ".tab-content.active {\n"
    "    display: block;\n"
    "}\n"
    "\n"
    "@keyframes fadeIn {\n"
    "    from { opacity: 0; transform: translateY(10px); }\n"
    "    to { opacity: 1; transform: translateY(0); }\n"
    "}\n"
    "\n"
    "/* Cards */\n"
    ".card-grid {\n"
    "    display: grid;\n"
    "    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n"
    "    gap: 20px;\n"
    "    margin-bottom: 20px;\n"
    "}\n"
    "\n"
    ".card {\n"
    "    background: var(--bg-card);\n"
    "    border-radius: var(--border-radius);\n"
    "    padding: 20px;\n"
    "    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);\n"
    "}\n"
    "\n"
    ".card h3 {\n"
    "    margin-bottom: 15px;\n"
    "    color: var(--accent-info);\n"
    "    font-size: 1.1rem;\n"
    "}\n"
    "\n"
    "/* Statistics */\n"
    ".stat-row {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    padding: 8px 0;\n"
    "    border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n"
    "}\n"
    "\n"
    ".stat-row:last-child {\n"
    "    border-bottom: none;\n"
    "}\n"
    "\n"
    ".stat-label {\n"
    "    color: var(--text-secondary);\n"
    "}\n"
    "\n"
    ".stat-value {\n"
    "    font-weight: bold;\n"
    "    color: var(--accent-success);\n"
    "}\n"
    "\n"
    "/* Buttons */\n"
    ".button-group {\n"
    "    display: flex;\n"
    "    gap: 10px;\n"
    "    flex-wrap: wrap;\n"
    "}\n"
    "\n"
    ".btn {\n"
    "    padding: 10px 20px;\n"
    "    border: none;\n"
    "    border-radius: var(--border-radius);\n"
    "    cursor: pointer;\n"
    "    font-size: 0.9rem;\n"
    "    transition: var(--transition);\n"
    "    font-weight: 500;\n"
    "}\n"
    "\n"
    ".btn:hover {\n"
    "    transform: translateY(-2px);\n"
    "    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);\n"
    "}\n"
    "\n"
    ".btn:active {\n"
    "    transform: translateY(0);\n"
    "}\n"
    "\n"
    ".btn-primary {\n"
    "    background: var(--accent-primary);\n"
    "    color: #fff;\n"
    "}\n"
    "\n"
    ".btn-secondary {\n"
    "    background: var(--bg-secondary);\n"
    "    color: var(--text-primary);\n"
    "    border: 1px solid rgba(255, 255, 255, 0.2);\n"
    "}\n"
    "\n"
    ".btn-success {\n"
    "    background: var(--accent-success);\n"
    "    color: #000;\n"
    "}\n"
    "\n"
    ".btn-danger {\n"
    "    background: var(--accent-danger);\n"
    "    color: #fff;\n"
    "}\n"
    "\n"
    ".btn-small {\n"
    "    padding: 5px 10px;\n"
    "    font-size: 0.8rem;\n"
    "}\n"
    "\n"
    "/* Forms */\n"
    ".form-group {\n"
    "    margin-bottom: 15px;\n"
    "}\n"
    "\n"
    ".form-group label {\n"
    "    display: block;\n"
    "    margin-bottom: 5px;\n"
    "    color: var(--text-secondary);\n"
    "    font-size: 0.9rem;\n"
    "}\n"
    "\n"
    ".form-group input,\n"
    ".form-group select {\n"
    "    width: 100%;\n"
    "    padding: 10px;\n"
    "    background: var(--bg-secondary);\n"
    "    border: 1px solid rgba(255, 255, 255, 0.2);\n"
    "    border-radius: var(--border-radius);\n"
    "    color: var(--text-primary);\n"
    "    font-size: 0.9rem;\n"
    "}\n"
    "\n"
    ".form-group input:focus,\n"
    ".form-group select:focus {\n"
    "    outline: none;\n"
    "    border-color: var(--accent-primary);\n"
    "}\n"
    "\n"
    "/* Tables */\n"
    ".table-container {\n"
    "    overflow-x: auto;\n"
    "    background: var(--bg-card);\n"
    "    border-radius: var(--border-radius);\n"
    "}\n"
    "\n"
    "table {\n"
    "    width: 100%;\n"
    "    border-collapse: collapse;\n"
    "}\n"
    "\n"
    "th, td {\n"
    "    padding: 12px;\n"
    "    text-align: left;\n"
    "    border-bottom: 1px solid rgba(255, 255, 255, 0.1);\n"
    "}\n"
    "\n"
    "th {\n"
    "    background: var(--bg-secondary);\n"
    "    color: var(--accent-info);\n"
    "    font-weight: 600;\n"
    "}\n"
    "\n"
    "tr:hover {\n"
    "    background: rgba(255, 255, 255, 0.05);\n"
    "}\n"
    "\n"
    "/* Toolbar */\n"
    ".toolbar {\n"
    "    display: flex;\n"
    "    gap: 10px;\n"
    "    margin-bottom: 15px;\n"
    "    flex-wrap: wrap;\n"
    "}\n"
    "\n"
    ".toolbar input {\n"
    "    flex: 1;\n"
    "    min-width: 200px;\n"
    "    padding: 10px;\n"
    "    background: var(--bg-card);\n"
    "    border: 1px solid rgba(255, 255, 255, 0.2);\n"
    "    border-radius: var(--border-radius);\n"
    "    color: var(--text-primary);\n"
    "}\n"
    "\n"
    "/* Handshake Indicator */\n"
    ".handshake-indicator {\n"
    "    display: flex;\n"
    "    gap: 10px;\n"
    "    justify-content: center;\n"
    "    margin: 20px 0;\n"
    "}\n"
    "\n"
    ".msg-indicator {\n"
    "    width: 50px;\n"
    "    height: 50px;\n"
    "    border-radius: 50%;\n"
    "    background: var(--bg-secondary);\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    font-weight: bold;\n"
    "    transition: var(--transition);\n"
    "}\n"
    "\n"
    ".msg-indicator.received {\n"
    "    background: var(--accent-success);\n"
    "    color: #000;\n"
    "}\n"
    "\n"
    "/* Progress Bar */\n"
    ".progress-bar {\n"
    "    width: 100%;\n"
    "    height: 20px;\n"
    "    background: var(--bg-secondary);\n"
    "    border-radius: 10px;\n"
    "    overflow: hidden;\n"
    "    margin: 10px 0;\n"
    "}\n"
    "\n"
    ".progress-fill {\n"
    "    height: 100%;\n"
    "    background: linear-gradient(90deg, var(--accent-primary), var(--accent-info));\n"
    "    transition: width 0.3s ease;\n"
    "}\n"
    "\n"
    "/* Log Container */\n"
    ".log-container {\n"
    "    background: var(--bg-card);\n"
    "    border-radius: var(--border-radius);\n"
    "    padding: 15px;\n"
    "    height: 400px;\n"
    "    overflow-y: auto;\n"
    "    font-family: 'Courier New', monospace;\n"
    "    font-size: 0.85rem;\n"
    "}\n"
    "\n"
    ".log-line {\n"
    "    padding: 3px 0;\n"
    "    border-bottom: 1px solid rgba(255, 255, 255, 0.05);\n"
    "}\n"
    "\n"
    ".log-time {\n"
    "    color: var(--text-secondary);\n"
    "}\n"
    "\n"
    ".log-level {\n"
    "    font-weight: bold;\n"
    "    margin: 0 5px;\n"
    "}\n"
    "\n"
    ".log-error .log-level { color: var(--accent-danger); }\n"
    ".log-warn .log-level { color: var(--accent-warning); }\n"
    ".log-info .log-level { color: var(--accent-info); }\n"
    ".log-debug .log-level { color: var(--text-secondary); }\n"
    "\n"
    "/* Warning Box */\n"
    ".warning-box {\n"
    "    background: rgba(244, 67, 54, 0.2);\n"
    "    border: 1px solid var(--accent-danger);\n"
    "    border-radius: var(--border-radius);\n"
    "    padding: 15px;\n"
    "    margin-bottom: 20px;\n"
    "    text-align: center;\n"
    "}\n"
    "\n"
    "/* File List */\n"
    ".file-list {\n"
    "    display: flex;\n"
    "    flex-direction: column;\n"
    "    gap: 5px;\n"
    "}\n"
    "\n"
    ".file-item {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "    padding: 10px;\n"
    "    background: var(--bg-secondary);\n"
    "    border-radius: var(--border-radius);\n"
    "}\n"
    "\n"
    "/* Canvas */\n"
    "canvas {\n"
    "    width: 100%;\n"
    "    height: 200px;\n"
    "    background: var(--bg-secondary);\n"
    "    border-radius: var(--border-radius);\n"
    "}\n"
    "\n"
    "/* Stats Text */\n"
    ".stats-text {\n"
    "    margin-top: 10px;\n"
    "    color: var(--text-secondary);\n"
    "    font-size: 0.9rem;\n"
    "}\n"
    "\n"
    "/* Footer */\n"
    "footer {\n"
    "    text-align: center;\n"
    "    padding: 20px;\n"
    "    color: var(--text-secondary);\n"
    "    font-size: 0.85rem;\n"
    "    border-top: 1px solid var(--bg-card);\n"
    "    margin-top: 20px;\n"
    "}\n"
    "\n"
    "/* Scrollbar */\n"
    "::-webkit-scrollbar {\n"
    "    width: 8px;\n"
    "    height: 8px;\n"
    "}\n"
    "\n"
    "::-webkit-scrollbar-track {\n"
    "    background: var(--bg-secondary);\n"
    "    border-radius: 4px;\n"
    "}\n"
    "\n"
    "::-webkit-scrollbar-thumb {\n"
    "    background: var(--bg-card);\n"
    "    border-radius: 4px;\n"
    "}\n"
    "\n"
    "::-webkit-scrollbar-thumb:hover {\n"
    "    background: var(--accent-primary);\n"
    "}\n"
    "\n"
    "/* Responsive */\n"
    "@media (max-width: 768px) {\n"
    "    .container {\n"
    "        padding: 10px;\n"
    "    }\n"
    "    \n"
    "    header h1 {\n"
    "        font-size: 1.5rem;\n"
    "    }\n"
    "\n"
    "    .lang-btn {\n"
    "        padding: 4px 10px;\n"
    "        font-size: 0.72rem;\n"
    "    }\n"
    "    \n"
    "    .card-grid {\n"
    "        grid-template-columns: 1fr;\n"
    "    }\n"
    "    \n"
    "    .tabs {\n"
    "        flex-wrap: wrap;\n"
    "    }\n"
    "    \n"
    "    .tab-btn {\n"
    "        flex: none;\n"
    "        min-width: 80px;\n"
    "        padding: 10px 15px;\n"
    "    }\n"
    "    \n"
    "    .button-group {\n"
    "        flex-direction: column;\n"
    "    }\n"
    "    \n"
    "    .btn {\n"
    "        width: 100%;\n"
    "    }\n"
    "    \n"
    "    th, td {\n"
    "        padding: 8px;\n"
    "        font-size: 0.85rem;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Animations */\n"
    "@keyframes pulse {\n"
    "    0%, 100% { opacity: 1; }\n"
    "    50% { opacity: 0.5; }\n"
    "}\n"
    "\n"
    ".pulse {\n"
    "    animation: pulse 2s infinite;\n"
    "}\n"
    "\n"
    "/* Utility Classes */\n"
    ".hidden {\n"
    "    display: none !important;\n"
    "}\n"
    "\n"
    ".text-center {\n"
    "    text-align: center;\n"
    "}\n"
    "\n"
    ".mt-10 {\n"
    "    margin-top: 10px;\n"
    "}\n"
    "\n"
    ".mb-10 {\n"
    "    margin-bottom: 10px;\n"
    "}\n"
    "\n";

const char APP_JS[] = 
    "/**\n"
    " * ESP32 WiFi Sniffer - Web Application\n"
    " */\n"
    "\n"
    "// ==================== 全局状态 ====================\n"
    "const state = {\n"
    "    connected: false,\n"
    "    ws: null,\n"
    "    reconnectInterval: 5000,\n"
    "    currentTab: 'dashboard',\n"
    "    lang: localStorage.getItem('lang') || 'en',\n"
    "    networks: [],\n"
    "    packets: [],\n"
    "    logs: [],\n"
    "    handshake: { msg1: false, msg2: false, msg3: false, msg4: false },\n"
    "    attack: { running: false, progress: 0 },\n"
    "    stats: {\n"
    "        totalPackets: 0,\n"
    "        networksFound: 0,\n"
    "        channel: 1,\n"
    "        rssi: 0\n"
    "    }\n"
    "};\n"
    "\n"
    "// ==================== 中英文翻译 ====================\n"
    "const i18n = {\n"
    "    en: {\n"
    "        // Header & Status\n"
    "        connected: 'Connected',\n"
    "        disconnected: 'Disconnected',\n"
    "        // Dashboard\n"
    "        statistics: 'Statistics',\n"
    "        totalPackets: 'Total Packets',\n"
    "        networksFound: 'Networks Found',\n"
    "        currentChannel: 'Current Channel',\n"
    "        rssi: 'RSSI',\n"
    "        wifiInfo: 'WiFi Info',\n"
    "        apIp: 'AP IP',\n"
    "        connectedClients: 'Connected Clients',\n"
    "        uptime: 'Uptime',\n"
    "        quickActions: 'Quick Actions',\n"
    "        packetRate: 'Packet Rate',\n"
    "        // Networks tab\n"
    "        networks: 'Networks',\n"
    "        filterNetworks: 'Filter networks...',\n"
    "        ssid: 'SSID',\n"
    "        bssid: 'BSSID',\n"
    "        channel: 'Channel',\n"
    "        security: 'Security',\n"
    "        packets: 'Packets',\n"
    "        actions: 'Actions',\n"
    "        refresh: 'Refresh',\n"
    "        select: 'Select',\n"
    "        capture: 'Capture',\n"
    "        // Capture tab\n"
    "        captureControl: 'Capture Control',\n"
    "        targetBssid: 'Target BSSID',\n"
    "        handshakeCapture: 'Handshake Capture',\n"
    "        noHandshake: 'No handshake captured',\n"
    "        handshakeCaptured: 'Handshake captured! Quality',\n"
    "        capturing: 'Capturing handshake...',\n"
    "        download: 'Download',\n"
    "        files: 'Files',\n"
    "        allHop: 'All (Hop)',\n"
    "        // Attack tab\n"
    "        attack: 'Attack',\n"
    "        warningLabel: 'Warning: These features are for authorized security testing only!',\n"
    "        deauthAttack: 'Deauth Attack',\n"
    "        targetStation: 'Target Station (optional)',\n"
    "        reasonCode: 'Reason Code',\n"
    "        startDeauth: 'Start Deauth',\n"
    "        stop: 'Stop',\n"
    "        dictionaryAttack: 'Dictionary Attack',\n"
    "        handshakeFile: 'Handshake File',\n"
    "        dictionary: 'Dictionary',\n"
    "        selectHandshake: 'Select handshake...',\n"
    "        selectDictionary: 'Select dictionary...',\n"
    "        startAttack: 'Start Attack',\n"
    "        tested: 'Tested',\n"
    "        speed: 'Speed',\n"
    "        pleaseEnterBssid: 'Please enter target BSSID',\n"
    "        confirmDeauth: 'WARNING: This will disconnect clients from the network. Continue?',\n"
    "        // Logs tab\n"
    "        logs: 'Logs',\n"
    "        clear: 'Clear',\n"
    "        export: 'Export',\n"
    "        allLevels: 'All Levels',\n"
    "        // Footer\n"
    "        securityResearch: 'For security research only',\n"
    "        webLoaded: 'Web interface loaded',\n"
    "        scanStarted: 'WiFi scan started',\n"
    "        sniffStarted: 'Packet sniffing started',\n"
    "        sniffStopped: 'Packet sniffing stopped',\n"
    "        networkSelected: 'Selected network',\n"
    "        handshakeStarted: 'Handshake capture started for',\n"
    "        deauthStarted: 'Deauth attack started on',\n"
    "        attackStopped: 'Attack stopped',\n"
    "        dictAttackStarted: 'Dictionary attack started',\n"
    "        deviceReset: 'Device reset',\n"
    "        selectHandshakeAndDict: 'Please select handshake file and dictionary',\n"
    "    },\n"
    "    zh: {\n"
    "        // Header & Status\n"
    "        connected: '已连接',\n"
    "        disconnected: '未连接',\n"
    "        // Dashboard\n"
    "        statistics: '统计信息',\n"
    "        totalPackets: '总数据包',\n"
    "        networksFound: '发现网络',\n"
    "        currentChannel: '当前信道',\n"
    "        rssi: '信号强度',\n"
    "        wifiInfo: 'WiFi 信息',\n"
    "        apIp: 'AP 地址',\n"
    "        connectedClients: '已连接客户端',\n"
    "        uptime: '运行时间',\n"
    "        quickActions: '快捷操作',\n"
    "        packetRate: '数据包速率',\n"
    "        // Networks tab\n"
    "        networks: '网络列表',\n"
    "        filterNetworks: '筛选网络...',\n"
    "        ssid: 'SSID',\n"
    "        bssid: 'BSSID',\n"
    "        channel: '信道',\n"
    "        security: '加密',\n"
    "        packets: '数据包',\n"
    "        actions: '操作',\n"
    "        refresh: '刷新',\n"
    "        select: '选中',\n"
    "        capture: '捕获',\n"
    "        // Capture tab\n"
    "        captureControl: '抓包控制',\n"
    "        targetBssid: '目标 BSSID',\n"
    "        handshakeCapture: '握手包捕获',\n"
    "        noHandshake: '未捕获到握手包',\n"
    "        handshakeCaptured: '握手包已捕获！质量',\n"
    "        capturing: '正在捕获握手包...',\n"
    "        download: '下载',\n"
    "        files: '文件列表',\n"
    "        allHop: '全信道跳频',\n"
    "        // Attack tab\n"
    "        attack: '攻击',\n"
    "        warningLabel: '⚠️ 警告：这些功能仅用于授权的安全测试！',\n"
    "        deauthAttack: 'Deauth 攻击',\n"
    "        targetStation: '目标设备 MAC（可选）',\n"
    "        reasonCode: '原因码',\n"
    "        startDeauth: '⚠️ 开始攻击',\n"
    "        stop: '停止',\n"
    "        dictionaryAttack: '字典攻击',\n"
    "        handshakeFile: '握手包文件',\n"
    "        dictionary: '字典文件',\n"
    "        selectHandshake: '选择握手包...',\n"
    "        selectDictionary: '选择字典...',\n"
    "        startAttack: '▶️ 开始攻击',\n"
    "        tested: '已测试',\n"
    "        speed: '速度',\n"
    "        pleaseEnterBssid: '请输入目标 BSSID',\n"
    "        confirmDeauth: '⚠️ 警告：这将断开目标网络的客户端连接。确定继续吗？',\n"
    "        // Logs tab\n"
    "        logs: '日志',\n"
    "        clear: '清空',\n"
    "        export: '导出',\n"
    "        allLevels: '所有级别',\n"
    "        // Footer\n"
    "        securityResearch: '仅供安全研究使用',\n"
    "        webLoaded: 'Web 界面已加载',\n"
    "        scanStarted: 'WiFi 扫描已启动',\n"
    "        sniffStarted: '数据包嗅探已启动',\n"
    "        sniffStopped: '数据包嗅探已停止',\n"
    "        networkSelected: '已选中网络',\n"
    "        handshakeStarted: '开始捕获握手包',\n"
    "        deauthStarted: 'Deauth 攻击已启动',\n"
    "        attackStopped: '攻击已停止',\n"
    "        dictAttackStarted: '字典攻击已启动',\n"
    "        deviceReset: '设备已重置',\n"
    "        selectHandshakeAndDict: '请选择握手包文件和字典文件',\n"
    "    }\n"
    "};\n"
    "\n"
    "function T(key) {\n"
    "    return i18n[state.lang][key] || key;\n"
    "}\n"
    "\n"
    "function toggleLanguage() {\n"
    "    state.lang = state.lang === 'en' ? 'zh' : 'en';\n"
    "    localStorage.setItem('lang', state.lang);\n"
    "    applyLanguage();\n"
    "}\n"
    "\n"
    "function applyLanguage() {\n"
    "    const btn = document.getElementById('lang-toggle');\n"
    "    btn.textContent = state.lang === 'en' ? 'EN | 中文' : '中文 | EN';\n"
    "    document.documentElement.lang = state.lang === 'en' ? 'en' : 'zh-CN';\n"
    "\n"
    "    // Tab buttons\n"
    "    document.querySelector('[data-tab=\"dashboard\"]').textContent = T('statistics');\n"
    "    document.querySelector('[data-tab=\"networks\"]').textContent = T('networks');\n"
    "    document.querySelector('[data-tab=\"capture\"]').textContent = T('captureControl');\n"
    "    document.querySelector('[data-tab=\"attack\"]').textContent = T('attack');\n"
    "    document.querySelector('[data-tab=\"logs\"]').textContent = T('logs');\n"
    "\n"
    "    // Dashboard cards in card-grid\n"
    "    const dashboardCards = document.querySelectorAll('#dashboard .card-grid .card');\n"
    "    if (dashboardCards[0]) {\n"
    "        dashboardCards[0].querySelector('h3').textContent = '📊 ' + T('statistics');\n"
    "        const labels = dashboardCards[0].querySelectorAll('.stat-label');\n"
    "        if (labels[0]) labels[0].textContent = T('totalPackets') + ':';\n"
    "        if (labels[1]) labels[1].textContent = T('networksFound') + ':';\n"
    "        if (labels[2]) labels[2].textContent = T('currentChannel') + ':';\n"
    "        if (labels[3]) labels[3].textContent = T('rssi') + ':';\n"
    "    }\n"
    "    if (dashboardCards[1]) {\n"
    "        dashboardCards[1].querySelector('h3').textContent = '📡 ' + T('wifiInfo');\n"
    "        const labels = dashboardCards[1].querySelectorAll('.stat-label');\n"
    "        if (labels[0]) labels[0].textContent = T('apIp') + ':';\n"
    "        if (labels[1]) labels[1].textContent = T('connectedClients') + ':';\n"
    "        if (labels[2]) labels[2].textContent = T('uptime') + ':';\n"
    "    }\n"
    "    if (dashboardCards[2]) {\n"
    "        dashboardCards[2].querySelector('h3').textContent = '🎯 ' + T('quickActions');\n"
    "    }\n"
    "\n"
    "    // Buttons\n"
    "    document.getElementById('btn-scan').textContent = state.lang === 'en' ? 'Start Scan' : '开始扫描';\n"
    "    document.getElementById('btn-sniff').textContent = state.lang === 'en' ? 'Start Sniff' : '开始抓包';\n"
    "    document.getElementById('btn-reset').textContent = state.lang === 'en' ? 'Reset' : '重置';\n"
    "\n"
    "    // Dashboard card 4 (outside card-grid)\n"
    "    const packetRateCard = document.querySelector('#dashboard > .card h3');\n"
    "    if (packetRateCard) packetRateCard.textContent = '📈 ' + T('packetRate');\n"
    "\n"
    "    // Networks tab\n"
    "    document.getElementById('btn-refresh-networks').textContent = '🔄 ' + T('refresh');\n"
    "    document.getElementById('network-filter').placeholder = T('filterNetworks');\n"
    "    const ths = document.querySelectorAll('#networks-table th');\n"
    "    if (ths[0]) ths[0].textContent = T('ssid');\n"
    "    if (ths[1]) ths[1].textContent = T('bssid');\n"
    "    if (ths[2]) ths[2].textContent = T('channel');\n"
    "    if (ths[3]) ths[3].textContent = T('rssi');\n"
    "    if (ths[4]) ths[4].textContent = T('security');\n"
    "    if (ths[5]) ths[5].textContent = T('packets');\n"
    "    if (ths[6]) ths[6].textContent = T('actions');\n"
    "\n"
    "    // Capture tab\n"
    "    const captureCards = document.querySelectorAll('#capture .card-grid .card');\n"
    "    if (captureCards[0]) {\n"
    "        captureCards[0].querySelector('h3').textContent = '📦 ' + T('captureControl');\n"
    "        const captureLabels = captureCards[0].querySelectorAll('label');\n"
    "        if (captureLabels[0]) captureLabels[0].textContent = T('channel') + ':';\n"
    "        if (captureLabels[1]) captureLabels[1].textContent = T('targetBssid') + ':';\n"
    "    }\n"
    "    document.getElementById('btn-capture-start').textContent = '▶️ ' + (state.lang === 'en' ? 'Start' : '开始');\n"
    "    document.getElementById('btn-capture-stop').textContent = '⏹️ ' + T('stop');\n"
    "\n"
    "    if (captureCards[1]) {\n"
    "        captureCards[1].querySelector('h3').textContent = '🤝 ' + T('handshakeCapture');\n"
    "    }\n"
    "    document.getElementById('handshake-text').textContent = T('noHandshake');\n"
    "    document.getElementById('btn-download-handshake').textContent = '⬇️ ' + T('download');\n"
    "\n"
    "    const filesCard = document.querySelector('#capture > .card h3');\n"
    "    if (filesCard) filesCard.textContent = '💾 ' + T('files');\n"
    "\n"
    "    // Update all select option text\n"
    "    const allHopOption = document.querySelector('#capture-channel option');\n"
    "    if (allHopOption) allHopOption.textContent = T('allHop');\n"
    "\n"
    "    // Attack tab\n"
    "    const warningBox = document.querySelector('#attack .warning-box');\n"
    "    if (warningBox) warningBox.innerHTML = '⚠️ <strong>' + T('warningLabel') + '</strong>';\n"
    "\n"
    "    const attackCards = document.querySelectorAll('#attack .card-grid .card');\n"
    "    if (attackCards[0]) {\n"
    "        attackCards[0].querySelector('h3').textContent = '💥 ' + T('deauthAttack');\n"
    "        const deauthLabels = attackCards[0].querySelectorAll('label');\n"
    "        if (deauthLabels[0]) deauthLabels[0].textContent = T('targetBssid') + ':';\n"
    "        if (deauthLabels[1]) deauthLabels[1].textContent = T('targetStation');\n"
    "        if (deauthLabels[2]) deauthLabels[2].textContent = T('reasonCode') + ':';\n"
    "    }\n"
    "    document.getElementById('btn-deauth-start').textContent = T('startDeauth');\n"
    "    document.getElementById('btn-deauth-stop').textContent = T('stop');\n"
    "\n"
    "    if (attackCards[1]) {\n"
    "        attackCards[1].querySelector('h3').textContent = '🔓 ' + T('dictionaryAttack');\n"
    "        const dictLabels = attackCards[1].querySelectorAll('label');\n"
    "        if (dictLabels[0]) dictLabels[0].textContent = T('handshakeFile') + ':';\n"
    "        if (dictLabels[1]) dictLabels[1].textContent = T('dictionary') + ':';\n"
    "    }\n"
    "    const selectOptions = document.querySelectorAll('#dict-handshake option');\n"
    "    if (selectOptions[0]) selectOptions[0].textContent = T('selectHandshake');\n"
    "    const dictOptions = document.querySelectorAll('#dict-file option');\n"
    "    if (dictOptions[0]) dictOptions[0].textContent = T('selectDictionary');\n"
    "    document.getElementById('btn-dict-start').textContent = T('startAttack');\n"
    "    document.getElementById('btn-dict-stop').textContent = T('stop');\n"
    "\n"
    "    // Logs tab\n"
    "    document.getElementById('btn-clear-logs').textContent = T('clear');\n"
    "    document.getElementById('btn-export-logs').textContent = T('export');\n"
    "    const logOptions = document.querySelectorAll('#log-level option');\n"
    "    if (logOptions[0]) logOptions[0].textContent = T('allLevels');\n"
    "\n"
    "    // Footer\n"
    "    const footerP = document.querySelector('footer p');\n"
    "    if (footerP) footerP.textContent = 'ESP32 WiFi Sniffer v1.0.0 | ' + T('securityResearch');\n"
    "}\n"
    "\n"
    "// ==================== WebSocket 连接 ====================\n"
    "function connectWebSocket() {\n"
    "    const wsUrl = `ws://${window.location.hostname}/ws`;\n"
    "    \n"
    "    state.ws = new WebSocket(wsUrl);\n"
    "    \n"
    "    state.ws.onopen = () => {\n"
    "        console.log('WebSocket connected');\n"
    "        state.connected = true;\n"
    "        updateConnectionStatus();\n"
    "        requestStatus();\n"
    "    };\n"
    "    \n"
    "    state.ws.onclose = () => {\n"
    "        console.log('WebSocket disconnected');\n"
    "        state.connected = false;\n"
    "        updateConnectionStatus();\n"
    "        setTimeout(connectWebSocket, state.reconnectInterval);\n"
    "    };\n"
    "    \n"
    "    state.ws.onerror = (error) => {\n"
    "        console.error('WebSocket error:', error);\n"
    "    };\n"
    "    \n"
    "    state.ws.onmessage = (event) => {\n"
    "        handleMessage(JSON.parse(event.data));\n"
    "    };\n"
    "}\n"
    "\n"
    "function updateConnectionStatus() {\n"
    "    const statusEl = document.getElementById('connection-status');\n"
    "    if (state.connected) {\n"
    "        statusEl.textContent = T('connected');\n"
    "        statusEl.className = 'status connected';\n"
    "    } else {\n"
    "        statusEl.textContent = T('disconnected');\n"
    "        statusEl.className = 'status disconnected';\n"
    "    }\n"
    "}\n"
    "\n"
    "function requestStatus() {\n"
    "    if (state.ws && state.ws.readyState === WebSocket.OPEN) {\n"
    "        state.ws.send(JSON.stringify({ cmd: 'get_status' }));\n"
    "    }\n"
    "}\n"
    "\n"
    "// ==================== 消息处理 ====================\n"
    "function handleMessage(data) {\n"
    "    switch (data.type) {\n"
    "        case 'status':\n"
    "            updateStatus(data);\n"
    "            break;\n"
    "        case 'scan_result':\n"
    "            addNetwork(data.data);\n"
    "            break;\n"
    "        case 'scan_complete':\n"
    "            addLog('info', T('scanStarted'));\n"
    "            break;\n"
    "        case 'packet':\n"
    "            handlePacket(data.data);\n"
    "            break;\n"
    "        case 'handshake':\n"
    "            updateHandshake(data.data);\n"
    "            break;\n"
    "        case 'attack_progress':\n"
    "            updateAttackProgress(data.data);\n"
    "            break;\n"
    "        case 'log':\n"
    "            addLog(data.level, data.message);\n"
    "            break;\n"
    "    }\n"
    "}\n"
    "\n"
    "function updateStatus(data) {\n"
    "    state.stats.totalPackets = data.packets || 0;\n"
    "    state.stats.networksFound = data.networks || 0;\n"
    "    state.stats.channel = data.channel || 1;\n"
    "    state.stats.rssi = data.rssi || 0;\n"
    "    \n"
    "    document.getElementById('stat-packets').textContent = state.stats.totalPackets;\n"
    "    document.getElementById('stat-networks').textContent = state.stats.networksFound;\n"
    "    document.getElementById('stat-channel').textContent = state.stats.channel;\n"
    "    document.getElementById('stat-rssi').textContent = state.stats.rssi + ' dBm';\n"
    "    document.getElementById('wifi-clients').textContent = data.wifi?.ap_clients || 0;\n"
    "    \n"
    "    // 更新模式标签\n"
    "    const modeBadge = document.getElementById('mode-badge');\n"
    "    const modes = ['IDLE', 'SCANNING', 'SNIFFING', 'HANDSHAKE', 'DEAUTH', 'ATTACK', 'WEB'];\n"
    "    modeBadge.textContent = modes[data.mode] || 'UNKNOWN';\n"
    "    \n"
    "    // 更新运行时间\n"
    "    const uptime = data.uptime || 0;\n"
    "    const hours = Math.floor(uptime / 3600);\n"
    "    const minutes = Math.floor((uptime % 3600) / 60);\n"
    "    const seconds = uptime % 60;\n"
    "    document.getElementById('stat-uptime').textContent = \n"
    "        `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;\n"
    "}\n"
    "\n"
    "function handlePacket(data) {\n"
    "    state.stats.totalPackets++;\n"
    "    document.getElementById('stat-packets').textContent = state.stats.totalPackets;\n"
    "    \n"
    "    // 更新图表\n"
    "    updatePacketChart();\n"
    "}\n"
    "\n"
    "function addNetwork(network) {\n"
    "    // 检查是否已存在\n"
    "    const existing = state.networks.find(n => n.bssid === network.bssid);\n"
    "    if (existing) {\n"
    "        Object.assign(existing, network);\n"
    "    } else {\n"
    "        state.networks.push(network);\n"
    "    }\n"
    "    \n"
    "    updateNetworksTable();\n"
    "}\n"
    "\n"
    "function updateNetworksTable() {\n"
    "    const tbody = document.getElementById('networks-tbody');\n"
    "    const filter = document.getElementById('network-filter')?.value.toLowerCase() || '';\n"
    "    \n"
    "    tbody.innerHTML = state.networks\n"
    "        .filter(n => !filter || n.ssid.toLowerCase().includes(filter) || n.bssid.toLowerCase().includes(filter))\n"
    "        .map(n => `\n"
    "            <tr>\n"
    "                <td>${escapeHtml(n.ssid)}</td>\n"
    "                <td>${n.bssid}</td>\n"
    "                <td>${n.channel}</td>\n"
    "                <td>${n.rssi} dBm</td>\n"
    "                <td>${n.auth}</td>\n"
    "                <td>${n.packets}</td>\n"
    "                <td>\n"
    "                    <button class=\"btn btn-small\" onclick=\"selectNetwork('${n.bssid}', ${n.channel})\">Select</button>\n"
    "                    <button class=\"btn btn-small btn-danger\" onclick=\"captureHandshake('${n.bssid}')\">Capture</button>\n"
    "                </td>\n"
    "            </tr>\n"
    "        `).join('');\n"
    "}\n"
    "\n"
    "function updateHandshake(data) {\n"
    "    state.handshake = {\n"
    "        msg1: data.msg1,\n"
    "        msg2: data.msg2,\n"
    "        msg3: data.msg3,\n"
    "        msg4: data.msg4\n"
    "    };\n"
    "    \n"
    "    // 更新指示器\n"
    "    document.getElementById('msg1').className = 'msg-indicator ' + (data.msg1 ? 'received' : '');\n"
    "    document.getElementById('msg2').className = 'msg-indicator ' + (data.msg2 ? 'received' : '');\n"
    "    document.getElementById('msg3').className = 'msg-indicator ' + (data.msg3 ? 'received' : '');\n"
    "    document.getElementById('msg4').className = 'msg-indicator ' + (data.msg4 ? 'received' : '');\n"
    "    \n"
    "    // 更新进度条\n"
    "    const quality = data.quality || 0;\n"
    "    document.getElementById('handshake-progress').style.width = quality + '%';\n"
    "    \n"
    "    // 更新文本\n"
    "    const statusText = data.complete ? \n"
    "        `✅ ${T('handshakeCaptured')}: ${quality}%` : \n"
    "        `⏳ ${T('capturing')} ${quality}%`;\n"
    "    document.getElementById('handshake-text').textContent = statusText;\n"
    "    \n"
    "    // 启用下载按钮\n"
    "    document.getElementById('btn-download-handshake').disabled = !data.valid;\n"
    "}\n"
    "\n"
    "function updateAttackProgress(data) {\n"
    "    state.attack.progress = data.progress || 0;\n"
    "    \n"
    "    const progressBar = document.querySelector('#dict-progress .progress-fill');\n"
    "    if (progressBar) {\n"
    "        progressBar.style.width = state.attack.progress + '%';\n"
    "    }\n"
    "    \n"
    "    const statsText = `${T('tested')}: ${data.tested}/${data.total} | ${T('speed')}: ${data.speed.toFixed(1)} p/s`;\n"
    "    document.getElementById('dict-stats').textContent = statsText;\n"
    "}\n"
    "\n"
    "function addLog(level, message) {\n"
    "    const timestamp = new Date().toLocaleTimeString();\n"
    "    state.logs.push({ timestamp, level, message });\n"
    "    \n"
    "    // 限制日志数量\n"
    "    if (state.logs.length > 1000) {\n"
    "        state.logs.shift();\n"
    "    }\n"
    "    \n"
    "    updateLogDisplay();\n"
    "}\n"
    "\n"
    "function updateLogDisplay() {\n"
    "    const container = document.getElementById('log-container');\n"
    "    const levelFilter = document.getElementById('log-level')?.value || 'all';\n"
    "    \n"
    "    const filtered = state.logs.filter(l => levelFilter === 'all' || l.level === levelFilter);\n"
    "    \n"
    "    container.innerHTML = filtered.map(l => `\n"
    "        <div class=\"log-line log-${l.level}\">\n"
    "            <span class=\"log-time\">${l.timestamp}</span>\n"
    "            <span class=\"log-level\">[${l.level.toUpperCase()}]</span>\n"
    "            <span class=\"log-message\">${escapeHtml(l.message)}</span>\n"
    "        </div>\n"
    "    `).join('');\n"
    "    \n"
    "    // 自动滚动到底部\n"
    "    container.scrollTop = container.scrollHeight;\n"
    "}\n"
    "\n"
    "// ==================== 图表 ====================\n"
    "let packetChart = null;\n"
    "let packetHistory = [];\n"
    "\n"
    "function initPacketChart() {\n"
    "    const canvas = document.getElementById('packet-chart');\n"
    "    if (!canvas) return;\n"
    "    \n"
    "    const ctx = canvas.getContext('2d');\n"
    "    \n"
    "    // 初始化历史数据\n"
    "    packetHistory = new Array(100).fill(0);\n"
    "    \n"
    "    drawChart(ctx);\n"
    "    \n"
    "    // 定期更新\n"
    "    setInterval(() => {\n"
    "        packetHistory.shift();\n"
    "        packetHistory.push(state.stats.totalPackets);\n"
    "        drawChart(ctx);\n"
    "    }, 1000);\n"
    "}\n"
    "\n"
    "function drawChart(ctx) {\n"
    "    const width = ctx.canvas.width;\n"
    "    const height = ctx.canvas.height;\n"
    "    \n"
    "    ctx.clearRect(0, 0, width, height);\n"
    "    \n"
    "    // 绘制网格\n"
    "    ctx.strokeStyle = '#333';\n"
    "    ctx.lineWidth = 1;\n"
    "    for (let i = 0; i < 5; i++) {\n"
    "        const y = (height / 4) * i;\n"
    "        ctx.beginPath();\n"
    "        ctx.moveTo(0, y);\n"
    "        ctx.lineTo(width, y);\n"
    "        ctx.stroke();\n"
    "    }\n"
    "    \n"
    "    // 绘制数据线\n"
    "    ctx.strokeStyle = '#4CAF50';\n"
    "    ctx.lineWidth = 2;\n"
    "    ctx.beginPath();\n"
    "    \n"
    "    const maxVal = Math.max(...packetHistory, 1);\n"
    "    \n"
    "    packetHistory.forEach((val, i) => {\n"
    "        const x = (width / (packetHistory.length - 1)) * i;\n"
    "        const y = height - (val / maxVal) * height * 0.9;\n"
    "        \n"
    "        if (i === 0) {\n"
    "            ctx.moveTo(x, y);\n"
    "        } else {\n"
    "            ctx.lineTo(x, y);\n"
    "        }\n"
    "    });\n"
    "    \n"
    "    ctx.stroke();\n"
    "}\n"
    "\n"
    "function updatePacketChart() {\n"
    "    // 图表会在定时器中更新\n"
    "}\n"
    "\n"
    "// ==================== API 调用 ====================\n"
    "async function apiCall(endpoint, method = 'GET', data = null) {\n"
    "    const options = {\n"
    "        method,\n"
    "        headers: {\n"
    "            'Content-Type': 'application/json'\n"
    "        }\n"
    "    };\n"
    "    \n"
    "    if (data) {\n"
    "        options.body = JSON.stringify(data);\n"
    "    }\n"
    "    \n"
    "    try {\n"
    "        const response = await fetch(`/api/${endpoint}`, options);\n"
    "        return await response.json();\n"
    "    } catch (error) {\n"
    "        console.error('API call failed:', error);\n"
    "        return { success: false, error: error.message };\n"
    "    }\n"
    "}\n"
    "\n"
    "// ==================== 操作函数 ====================\n"
    "async function startScan() {\n"
    "    const result = await apiCall('scan');\n"
    "    if (result.success) {\n"
    "        state.networks = [];\n"
    "    }\n"
    "}\n"
    "\n"
    "async function startSniff() {\n"
    "    const channel = document.getElementById('capture-channel')?.value || 0;\n"
    "    const result = await apiCall(`capture/start?channel=${channel}`, 'POST');\n"
    "    if (result.success) addLog('info', T('sniffStarted'));\n"
    "}\n"
    "\n"
    "async function stopSniff() {\n"
    "    const result = await apiCall('capture/stop', 'POST');\n"
    "    if (result.success) addLog('info', T('sniffStopped'));\n"
    "}\n"
    "\n"
    "function selectNetwork(bssid, channel) {\n"
    "    document.getElementById('capture-bssid').value = bssid;\n"
    "    document.getElementById('deauth-bssid').value = bssid;\n"
    "    document.getElementById('capture-channel').value = channel;\n"
    "    addLog('info', `${T('networkSelected')}: ${bssid} (CH${channel})`);\n"
    "}\n"
    "\n"
    "async function captureHandshake(bssid) {\n"
    "    const result = await apiCall(`capture/start?bssid=${bssid}`, 'POST');\n"
    "    if (result.success) {\n"
    "        addLog('info', `${T('handshakeStarted')} ${bssid}`);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function startDeauth() {\n"
    "    const bssid = document.getElementById('deauth-bssid').value;\n"
    "    const station = document.getElementById('deauth-station').value;\n"
    "    const reason = document.getElementById('deauth-reason').value;\n"
    "    \n"
    "    if (!bssid) {\n"
    "        alert(T('pleaseEnterBssid'));\n"
    "        return;\n"
    "    }\n"
    "    \n"
    "    if (!confirm(T('confirmDeauth'))) {\n"
    "        return;\n"
    "    }\n"
    "    \n"
    "    const params = new URLSearchParams({ bssid, reason });\n"
    "    if (station) params.append('station', station);\n"
    "    \n"
    "    const result = await apiCall(`attack/start?${params.toString()}`, 'POST');\n"
    "    if (result.success) {\n"
    "        addLog('warning', `${T('deauthStarted')} ${bssid}`);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function stopDeauth() {\n"
    "    const result = await apiCall('attack/stop', 'POST');\n"
    "    if (result.success) addLog('info', T('attackStopped'));\n"
    "}\n"
    "\n"
    "async function startDictAttack() {\n"
    "    const handshake = document.getElementById('dict-handshake').value;\n"
    "    const dict = document.getElementById('dict-file').value;\n"
    "    \n"
    "    if (!handshake || !dict) {\n"
    "        alert(T('selectHandshakeAndDict'));\n"
    "        return;\n"
    "    }\n"
    "    \n"
    "    const result = await apiCall(`attack/start?type=dict&handshake=${handshake}&dict=${dict}`, 'POST');\n"
    "    if (result.success) {\n"
    "        addLog('info', T('dictAttackStarted'));\n"
    "        state.attack.running = true;\n"
    "    }\n"
    "}\n"
    "\n"
    "async function stopDictAttack() {\n"
    "    const result = await apiCall('attack/stop', 'POST');\n"
    "    if (result.success) {\n"
    "        addLog('info', T('attackStopped'));\n"
    "        state.attack.running = false;\n"
    "    }\n"
    "}\n"
    "\n"
    "async function downloadHandshake() {\n"
    "    window.location.href = '/api/handshake/download?format=hccapx';\n"
    "}\n"
    "\n"
    "async function downloadCapture() {\n"
    "    window.location.href = '/api/capture/download';\n"
    "}\n"
    "\n"
    "async function resetDevice() {\n"
    "    if (!confirm('Reset all state?')) return;\n"
    "    \n"
    "    const result = await apiCall('reset', 'POST');\n"
    "    if (result.success) {\n"
    "        addLog('info', T('deviceReset'));\n"
    "        state.networks = [];\n"
    "        state.logs = [];\n"
    "        updateNetworksTable();\n"
    "        updateLogDisplay();\n"
    "    }\n"
    "}\n"
    "\n"
    "// ==================== 工具函数 ====================\n"
    "function escapeHtml(text) {\n"
    "    const div = document.createElement('div');\n"
    "    div.textContent = text;\n"
    "    return div.innerHTML;\n"
    "}\n"
    "\n"
    "// ==================== 事件监听 ====================\n"
    "document.addEventListener('DOMContentLoaded', () => {\n"
    "    // 应用语言设置\n"
    "    applyLanguage();\n"
    "\n"
    "    // 连接 WebSocket\n"
    "    connectWebSocket();\n"
    "    \n"
    "    // 初始化图表\n"
    "    initPacketChart();\n"
    "    \n"
    "    // 标签页切换\n"
    "    document.querySelectorAll('.tab-btn').forEach(btn => {\n"
    "        btn.addEventListener('click', () => {\n"
    "            const tab = btn.dataset.tab;\n"
    "            \n"
    "            // 更新按钮状态\n"
    "            document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));\n"
    "            btn.classList.add('active');\n"
    "            \n"
    "            // 更新内容显示\n"
    "            document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));\n"
    "            document.getElementById(tab).classList.add('active');\n"
    "            \n"
    "            state.currentTab = tab;\n"
    "        });\n"
    "    });\n"
    "    \n"
    "    // 按钮事件\n"
    "    document.getElementById('btn-scan')?.addEventListener('click', startScan);\n"
    "    document.getElementById('btn-sniff')?.addEventListener('click', startSniff);\n"
    "    document.getElementById('btn-reset')?.addEventListener('click', resetDevice);\n"
    "    document.getElementById('btn-refresh-networks')?.addEventListener('click', startScan);\n"
    "    document.getElementById('btn-capture-start')?.addEventListener('click', startSniff);\n"
    "    document.getElementById('btn-capture-stop')?.addEventListener('click', stopSniff);\n"
    "    document.getElementById('btn-deauth-start')?.addEventListener('click', startDeauth);\n"
    "    document.getElementById('btn-deauth-stop')?.addEventListener('click', stopDeauth);\n"
    "    document.getElementById('btn-dict-start')?.addEventListener('click', startDictAttack);\n"
    "    document.getElementById('btn-dict-stop')?.addEventListener('click', stopDictAttack);\n"
    "    document.getElementById('btn-download-handshake')?.addEventListener('click', downloadHandshake);\n"
    "    document.getElementById('btn-clear-logs')?.addEventListener('click', () => {\n"
    "        state.logs = [];\n"
    "        updateLogDisplay();\n"
    "    });\n"
    "    document.getElementById('btn-export-logs')?.addEventListener('click', () => {\n"
    "        const blob = new Blob([state.logs.map(l => `[${l.timestamp}] [${l.level}] ${l.message}`).join('\\n')], \n"
    "                              { type: 'text/plain' });\n"
    "        const url = URL.createObjectURL(blob);\n"
    "        const a = document.createElement('a');\n"
    "        a.href = url;\n"
    "        a.download = 'sniffer-logs.txt';\n"
    "        a.click();\n"
    "    });\n"
    "    \n"
    "    // 过滤器\n"
    "    document.getElementById('network-filter')?.addEventListener('input', updateNetworksTable);\n"
    "    document.getElementById('log-level')?.addEventListener('change', updateLogDisplay);\n"
    "    \n"
    "    // 定期请求状态\n"
    "    setInterval(requestStatus, 5000);\n"
    "    \n"
    "    // 初始日志\n"
    "    addLog('info', 'Web interface loaded');\n"
    "});\n"
    "\n";

#endif
